import type {
  CleanReportDoc,
  ExclusionDoc,
  ReportDoc,
  ReviewedDoc,
  RunDoc,
  ScoreGridDoc,
  TopNCsvRow,
  WeightSetDoc,
} from "./types";

export const MOCK_RUN: RunDoc = {
  run_id: "r_demo_mock_001",
  domain: "흡연",
  mode: "hitl",
  status: "succeeded",
  started_at: "2026-08-11T09:00:00Z",
  finished_at: "2026-08-11T09:01:00Z",
  error: null,
  artifacts: {
    reviewed: "/mock/reviewed.json",
    clean_report: "/mock/clean_report.json",
    exclusion: "/mock/exclusion.json",
    report: "/mock/report.json",
    weight_set: "/mock/weight_set.json",
    score_grid: "/mock/score_grid.json",
    topN: "/mock/topN.csv",
  },
  steps: [
    { id: "step1", label: "데이터 입력 및 감리", status: "done", sec: 2 },
    { id: "step2", label: "가중치 설정 및 입지선정", status: "done", sec: 3 },
    { id: "step3", label: "다자간 공청회 시뮬레이션", status: "done", sec: 5 },
  ],
};

export const MOCK_REVIEWED: ReviewedDoc = {
  facility_inference: {
    facility: "스마트 흡연부스",
    region: "서울특별시 용산구",
    source_input: "흡연",
    confirmed: true,
    근거: "서울특별시 흡연부스 설치 및 간접흡연 피해방지 조례",
    mismatch: false,
    mismatch_reason: null,
  },
  results: [
    {
      dataset_id: "ds_01_smoking_area",
      dataset_name: "기존 흡연시설 현황",
      hitl_flags: [],
      roles: [
        {
          role: "hard_exclusion",
          facility_type: "기존 흡연구역",
          배제반경_m: 20,
          need_review: false,
        },
      ],
    },
    {
      dataset_id: "ds_02_school_zone",
      dataset_name: "학교위생정화구역 및 어린이집",
      hitl_flags: [],
      roles: [
        {
          role: "hard_exclusion",
          facility_type: "어린이 보호구역",
          배제반경_m: 50,
          need_review: false,
        },
      ],
    },
    {
      dataset_id: "ds_03_bus_stop",
      dataset_name: "버스정류장 및 지하철 출입구",
      hitl_flags: [],
      roles: [
        {
          role: "negative_factor",
          facility_type: "버스정류장",
          배제반경_m: null,
          need_review: false,
        },
      ],
    },
  ],
} as any;

export const MOCK_CLEAN_REPORT: CleanReportDoc = {
  results: [
    {
      dataset_id: "ds_01_smoking_area",
      filename: "ds_01_smoking_area.csv",
      roles: ["hard_exclusion"],
      reference_only: false,
      gis_input: true,
      rows_before: 120,
      rows_after: 118,
    },
    {
      dataset_id: "ds_02_school_zone",
      filename: "ds_02_school_zone.csv",
      roles: ["hard_exclusion"],
      reference_only: false,
      gis_input: true,
      rows_before: 45,
      rows_after: 45,
    },
    {
      dataset_id: "ds_03_bus_stop",
      filename: "ds_03_bus_stop.csv",
      roles: ["negative_factor"],
      reference_only: false,
      gis_input: true,
      rows_before: 310,
      rows_after: 305,
    },
  ],
} as any;

export const MOCK_EXCLUSION: ExclusionDoc = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Polygon", coordinates: [] },
      properties: {
        dataset_id: "ds_01_smoking_area",
        radius_m: 20,
        verdict: "적용 확정",
        reason: "기존 흡연구역 반경 20m 이내 중복 설치 금지",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Polygon", coordinates: [] },
      properties: {
        dataset_id: "ds_02_school_zone",
        radius_m: 50,
        verdict: "적용 확정",
        reason: "국민건강증진법 제9조: 학교 및 어린이집 경계 50m 이내 금연구역",
      },
    },
  ],
} as any;

export const MOCK_REPORT: ReportDoc = {
  domain: "흡연",
  facility: "스마트 흡연부스",
  region: "서울특별시 용산구",
  summary: {
    total_parcels: 1420,
    eligible_parcels: 850,
    topn_count: 5,
    exclusion_union_km2: 1.85,
  },
  topn: [
    { PNU: "1117010100100120000", score: 94.5, JIBUN: "서울특별시 용산구 이태원동 12-1" },
    { PNU: "1117010100100150001", score: 89.2, JIBUN: "서울특별시 용산구 이태원동 15-1" },
    { PNU: "1117010100100200003", score: 86.8, JIBUN: "서울특별시 용산구 한남동 20-3" },
    { PNU: "1117010100100280000", score: 82.1, JIBUN: "서울특별시 용산구 용산동 28" },
    { PNU: "1117010100100340002", score: 79.4, JIBUN: "서울특별시 용산구 청파동 34-2" },
  ],
  charts: {},
} as any;

export const MOCK_WEIGHT_SET: WeightSetDoc = {
  domain: "흡연",
  facility: "스마트 흡연부스",
  region: "서울특별시 용산구",
  engine_version: "v2.0",
  generated_at: "2026-08-11T09:00:00Z",
  inputs: {},
  hitl: {
    radius_confirmed: true,
    weight_confirmed: true,
    value_source: "human",
  },
  alpha: 0.5,
  n_candidates: 850,
  candidate_unit: "필지",
  candidate_source: {},
  indicators: [
    {
      id: "ind_01",
      kind: "stat",
      direction: "cost",
      components: { geo: "ds_03_bus_stop" },
      radius_m: 100,
      radius_source: "human",
      radius_rationale: "유동인구가 많을수록 간접흡연 피해 방지를 위한 스마트 흡연부스 우수 입지",
      seed_rationale: null,
      sparse_excluded: false,
      w_human: 0.45,
      w_human_source: "human",
      direction_source: "human",
      direction_llm: "cost",
      direction_conflict: null,
      adjusted_at: "2026-08-11T09:00:00Z",
      w_critic: 0.40,
      w_critic_ci: { mean: 0.40, std: 0.05, ci_low: 0.35, ci_high: 0.45 },
      w_final: 0.425,
    },
    {
      id: "ind_02",
      kind: "spatial",
      direction: "cost",
      components: { geo: "ds_01_smoking_area" },
      radius_m: 200,
      radius_source: "human",
      radius_rationale: "기존 보건소/흡연부스간 적정 커버리지 확보",
      seed_rationale: null,
      sparse_excluded: false,
      w_human: 0.35,
      w_human_source: "human",
      direction_source: "human",
      direction_llm: "cost",
      direction_conflict: null,
      adjusted_at: "2026-08-11T09:00:00Z",
      w_critic: 0.30,
      w_critic_ci: null,
      w_final: 0.325,
    },
    {
      id: "ind_03",
      kind: "admin",
      direction: "benefit",
      components: { val: "land_ownership" },
      radius_m: null,
      radius_source: "human",
      radius_rationale: "사유지 매입비용 절감 및 신속한 행정 집행 가능성",
      seed_rationale: null,
      sparse_excluded: false,
      w_human: 0.20,
      w_human_source: "human",
      direction_source: "human",
      direction_llm: "benefit",
      direction_conflict: null,
      adjusted_at: "2026-08-11T09:00:00Z",
      w_critic: 0.30,
      w_critic_ci: null,
      w_final: 0.250,
    },
  ],
  notes: {
    critic_method: "standard",
    sparse_threshold: 0.1,
    sparse_excluded_ids: [],
    weight_meaning: "mixed",
  },
  decay: { func: "linear", sigma_ratio: 0.5 },
  scale: "minmax",
  diagnostics: {},
} as any;

export const MOCK_SCORE_GRID: ScoreGridDoc = {
  rows: [
    { PNU: "1117010100100120000", score: 94.5, rank: 1 },
    { PNU: "1117010100100150001", score: 89.2, rank: 2 },
    { PNU: "1117010100100200003", score: 86.8, rank: 3 },
  ],
} as any;

export const MOCK_TOPN: TopNCsvRow[] = [
  {
    parcel_idx: 1,
    from_rep: true,
    PNU: "1117010100100120000",
    JIBUN: "이태원동 12-1",
    지목: "대",
    면적: 240,
    내접폭: 12,
    법정동코드: "1117010100",
    국유_건수: 1,
    국유_지분면적: 240,
    국유_지분율: 1.0,
    국유_지번일치: true,
    점수: 94.5,
    커버기여: 0.35,
    누적커버율: 0.35,
    순위: 1,
    경도: 126.9892,
    위도: 37.5345,
  },
  {
    parcel_idx: 2,
    from_rep: true,
    PNU: "1117010100100150001",
    JIBUN: "이태원동 15-1",
    지목: "대",
    면적: 180,
    내접폭: 10,
    법정동코드: "1117010100",
    국유_건수: 1,
    국유_지분면적: 180,
    국유_지분율: 1.0,
    국유_지번일치: true,
    점수: 89.2,
    커버기여: 0.28,
    누적커버율: 0.63,
    순위: 2,
    경도: 126.9915,
    위도: 37.5361,
  },
];
